### ISSUE TITLE
Curator 5x package name change

### ISSUE THREAD

**Issue by drudnev** [mvisonneau/puppet-curator#13]
Curator 5.x no longer using 'python-elasticsearch-curator'
 - elasticsearch-curator-5.5.4-1 
This appears to be true for both RedHat and Debian repositories. 

Hiera override for package name only works if manage_repository = false. 
Following is a workaround for issue described.
```
curator::repository_version: '5'
curator::package_name: 'elasticsearch-curator'
curator::package_provider: 'yum'
curator::manage_repository: false 
```

**Comment by drudnev** [comment]
Pull request #15 should fix this. Repo #5 is now default with correct package name. Anyone that still using version should now be able to set repo version / package name. 
```
curator::repository_version: '4'
curator::package_name: 'python-elasticsearch-curator'
```

**Comment by mvisonneau** [comment]
thanks for the fix @drudnev !
