### ISSUE TITLE
Need to make it work for Puppet 5.x 

### ISSUE THREAD

**Issue by mvisonneau** [mvisonneau/puppet-curator#2]

**Comment by wojukasz** [comment]
As workaround for **puppet 5** I managed to made it work using ` manage_repository => false,` .   
It also required adding `*` to `value: logstash-logs` in hiera (so `value: logstash-logs*`)   
 
Tested it with `curator --config /etc/curator/curator.yml --dry-run /etc/curator/action_logstash-logs-indices-delete.yml`

**Comment by mvisonneau** [comment]
Thanks for the feedback @wojukasz , I need to get my head into it 😅

**Comment by drudnev** [comment]
Is this for puppet 5 or curator 5 ?

**Comment by wojukasz** [comment]
workaround for puppet 5

**Comment by smortex** [comment]
What Puppet 5 specific issue did you run into?  I could use the module with Puppet 6 on Debian without any Puppet-related issue (however, I had to tweak the repository because Debian stretch has a newer version of OpenSSL, see #17 if it rings a bell).

**Comment by mvisonneau** [comment]
I've managed to get it working as well on Puppet 6, closing this one 👌
