### ISSUE TITLE
Permissions should be tighter IMO

### ISSUE THREAD

**Issue by TJM** [mvisonneau/puppet-curator#21]
I realize you made the actual curator.yml file `0660` which is not world readable, but IMO we don't need the general public poking around in the curator config dir at all. I suggest `0750` instead of `0755`

I also tend to prefer "puppet managed" files to be read only (6->4), at least by filesystem permissions.  I realize that the owner of the file or root can override it, but that provides a small measure of suggestion. ;) 

In the end, each person may have different reasons for different permissions, so I suggest to make the "mode" be a parameter, so that people can set it however they want.

Unless there are any objections, I can probably make a PR for this.

~tommy

**Comment by mvisonneau** [comment]
That sounds perfectly good to me, feel free to submit a PR! :)
