### ISSUE TITLE
stdlibs 6 or 7?

### ISSUE THREAD

**Issue by djtecha** [mvisonneau/puppet-curator#23]
Hello, wondering if this project is still alive? if so would it be possible to update the stdlib dependency to allow up to 7.0.0? Currently it's stuck at 5.0.0

**Comment by mvisonneau** [comment]
👋 hey @djtecha, quite late on this but if you are still looking into it, I just released a new version of the module with updated dependencies 👍

**Comment by djtecha** [comment]
Nice, better late then never :)
