### ISSUE TITLE
Command ($which curator ) inside cron is not parse

### ISSUE THREAD

**Issue by ghost** [mvisonneau/puppet-curator#5]
Hello,

I am using ubuntu 16.04 , the cron doesn't work because it doesn't parse the 'which curator' command

> CRON[1790]: (curator) CMD ($(which curator) /etc/curator/action_purge_syslog_linux_over_30days.yml> /dev/null 2>&1)
CRON[1789]: (curator) CMD ($(which curator) /etc/curator/action_purge_filebeat_over_30days.yml> /dev/null 2>&1)

 
So I set the full path of the curator binary inside job.pp:

> cron { "curator_${name}":
    ensure   => $ensure,
    command  => "/usr/local/bin/curator ${::curator::config_path}/action_${action}.yml> /dev/null 2>&1",
    hour     => $hour,
    minute   => $minute,
    month    => $month,
    monthday => $monthday,
    user     => $user,
    weekday  => $weekday,
  }

And now it's works

`CRON[25048]: (curator) CMD (/usr/local/bin/curator /etc/curator/action_purge_filebeat_over_30days.yml> /dev/null 2>&1)`

**Comment by mvisonneau** [comment]
I've tested it on Ubuntu 16.04 as well and it works fine. I believe the error is due to something else. 🤔

**Comment by sergii-sakharov** [comment]
Probably due to docker image not having which package installed?

**Comment by mvisonneau** [comment]
You should now be able to configure it yourself : 
https://github.com/mvisonneau/puppet-curator/blob/master/manifests/init.pp#L11
