### ISSUE TITLE
job hours are passed as string to cron instead of object

### ISSUE THREAD

**Issue by sergii-sakharov** [mvisonneau/puppet-curator#8]
E.g. following works:

  cron { "curator_${name}":
.....
    hour     => [2,3,4],
.....
  }

While job wraps hour in a string and its now not possible to pass an array. Tried following:
hour: '[3,4,5]'
hour: '3,4,5'

The workaround is to create a job per time slot

**Comment by mvisonneau** [comment]
Indeed, I just pushed a fix 👍 thanks!
