### ISSUE TITLE
master is broken

### ISSUE THREAD

**Issue by sergii-sakharov** [mvisonneau/puppet-curator#9]
Hi there,

there are a few minor syntax errors: 
1. commas missing/redundant in action.pp;
2. missing ']' in job.pp

there is also a bigger issue when those have been cleared:
Error: Evaluation Error: A Type's size constraint arguments must be a single Integer type, or 1-2 integers (or default). Got an Enum-Type (file: /etc/puppet/modules/curator/manifests/job.pp, line: 9, column: 45) on node .....

**Comment by mvisonneau** [comment]
sorry about that, I did not take the time to try it yet. It should be fixed by #10 
as soon as I'll be able to test those changes I'll release a new version.
